application: github-intellij-plugin
version: 2
runtime: go
api_version: go1

skip_files:
  - wrigi.iml
  - .idea/
  - .git/
  - .gitignore

handlers:
  - url: /update
    script: _go_app
    login: admin
  - url: /.*
    script: _go_app